name: Windows Release Build
on:
  workflow_call:
    inputs:
      build-version:
        description: 'The version to build'
        required: true
        type: string
      release-branch:
        description: 'The branch to build'
        required: true
        type: string

jobs:
  windows-build:
    name: "zen-browser/desktop (${{ matrix.generic == true && 'Generic' || 'Specific' }}) - Windows ARM64 build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        generic: [true, false]

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Install Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: actions/checkout@v4
        with:
          repository: zen-browser/desktop
          ref: ${{ inputs.release-branch }}
          submodules: recursive

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Load surfer CI setup
        run: pnpm surfer ci --brand ${{ inputs.release-branch }} --display-version ${{ inputs.build-version }}

      - name: Download
        run: pnpm surfer download

      - name: 'win-cross Cache'
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5
        id: cache-win-cross
        uses: actions/cache@v4
        with:
          path: ${HOME}/win-cross
          key: win-cross

      - name: Configure sccache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Setup For Windows
        if: steps.cache-win-cross.outputs.cache-hit != 'true'
        run: |
          set -x
          mkdir -p ~/win-cross
          cd engine/

          echo Setup wine
          aria2c "https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-1.toolchains.v3.linux64-wine.latest/artifacts/public%2Fbuild%2Fwine.tar.zst" -o wine.tar.zst
          tar --zstd -xvf wine.tar.zst -C ~/win-cross
          rm wine.tar.zst

          echo Setup Visual Studio
          sudo apt install -y msitools python3-pip
          ./mach python --virtualenv build taskcluster/scripts/misc/get_vs.py build/vs/vs2022.yaml ~/win-cross/vs2022

      - name: Bootstrap
        run: |
          set -x
          cd engine/

          chmod -R +x "$(echo ~)/win-cross/vs2022" || true

          cd ..
          npm install -g pnpm
          export SURFER_PLATFORM="win64-aarch64"
          pnpm surfer bootstrap

          cd engine/
          ls ~/.mozbuild/clang/lib/clang/
          echo "export LIB=\"$(cd ~/.mozbuild/clang/lib/clang/* && cd lib/windows && pwd)\"" >> ../configs/common/mozconfig
          cat ../configs/common/mozconfig

          sudo apt-get update
          sudo apt-get install dos2unix

          ls ~/win-cross/wine || true
          ls ~/win-cross/vs2022 || true

      - name: setup Rust
        run: |
          cd engine/

          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.79
          source $HOME/.cargo/env

          rustup target add aarch64-pc-windows-msvc
          cargo install cargo-download
          cargo download -x windows=0.58.0
          #? https://github.com/mozilla/sccache#known-caveats
          export CARGO_INCREMENTAL=0

          echo "" >> ../configs/common/mozconfig
          echo "export MOZ_WINDOWS_RS_DIR=$(pwd)/windows-0.58.0" >> ../configs/common/mozconfig

      - name: Import
        env:
          SURFER_COMPAT: ${{ matrix.generic == true }}
        run: pnpm surfer import --verbose

      - name: Build language packs
        run: sh scripts/download-language-packs.sh

      - name: Build
        env:
          SURFER_COMPAT: ${{ matrix.generic == true }}
        run: |
          set -x
          dos2unix configs/windows/mozconfig
          export SURFER_PLATFORM="win32"
          export ZEN_CROSS_COMPILING=1
          sh .github/workflows/src/release-build.sh

      - name: Package
        env:
          SURFER_COMPAT: ${{ matrix.generic == true }}
        run: |
          set -x
          export SURFER_PLATFORM="win32"
          pnpm package
          mv ./dist/zen-$(pnpm surfer get version | xargs).en-US.win64.zip zen.win64.zip
          ls ./dist
          ls .

      - name: 🐛 Debug Session
        if: ${{ failure() }}
        uses: Warpbuilds/gha-debug@v1.3
        timeout-minutes: 15

      - name: Rename artifacts
        run: |
          mv ./dist/output.mar windows${{ matrix.generic == true && '-generic' || '' }}.mar
          mv ./dist/zen.installer.exe ./zen.installer${{ matrix.generic == true && '-generic' || '' }}.exe

      - name: Remove unnecessary files from obj
        run: |
          set -x
          find engine/obj-arm64-pc-windows-msvc/ -mindepth 1 -maxdepth 1 -type d -not -name 'dist' -exec rm -rf {} \;
          find engine/obj-arm64-pc-windows-msvc/ -mindepth 1 -maxdepth 1 -type f -not -name 'dist' -exec rm -f {} \;

      - name: Upload dist object
        uses: actions/upload-artifact@v4
        with:
          name: windows-arm64-obj-${{ matrix.generic == true && 'generic' || 'specific' }}
          path: engine/obj-arm64-pc-windows-msvc/